# Generated by Django 4.2.7 on 2023-11-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
