# Generated by Django 4.2.7 on 2023-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=225, unique=True, verbose_name='Название категории'),
        ),
    ]
