# Generated by Django 4.2.7 on 2023-11-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default='Сладкий котик ~(=^‥^)/', max_length=100, verbose_name='О себе'),
        ),
    ]
