# Generated by Django 4.2.7 on 2023-11-11 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_options_alter_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_customuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../../static/default/default_coal.png', upload_to='UserImages', verbose_name='Фото')),
                ('bio', models.CharField(default='Сладкий котик ~(=^‥^)/', max_length=100, verbose_name='О себе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фото и описание пользователя',
                'verbose_name_plural': 'Фото и описании полоьзователей',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
