# Generated by Django 4.2.7 on 2023-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdop_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdop',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важность чела'),
        ),
    ]
