# Generated by Django 4.2.7 on 2023-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Заголовок публикации')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='PostImages', verbose_name='Фото публикации')),
                ('category', models.ManyToManyField(blank=True, null=True, to='category.category')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
