# Generated by Django 4.2.7 on 2023-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_title'),
        ('post', '0003_alter_post_options_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='category.category', verbose_name='Категория'),
        ),
    ]
